### PR TITLE
+ Fully translated lt.po

### PR DESCRIPTION
**Pull request by embar-**
Lithuanian translation of openSUSE Leap 42.1 release notes

### CODE REVIEW

**Comment by coolo** [comment]
I think this should go to weblate, but I'm not sure :)

**Comment by embar-** [comment]
There is some issues with Webplate regarding Lithuanian language:
it modifies PO header in wrong way: swith to 3 plural forms instead of 4.
See https://github.com/nijel/weblate/issues/900

**Comment by embar-** [comment]
Please accept!

**Comment by sknorr** [comment]
@embar- Is this request still relevant? (The underlying Weblate seems to be unfixed so far... but the localization is probably outdated. Also, if you do a new pull request, do it towards the branch `Leap_42.1` [which is new].)

**Comment by embar-** [comment]
This request no longer actual

**Comment by sknorr** [comment]
Sorry for letting this bitrot around here. :(

**Pull request closed without merging**
