### PR TITLE
Document removal of slapi-nis 

### PR DESCRIPTION
**Pull request by Firstyear**
Slapi nis has been requested for removal in https://build.opensuse.org/request/show/760508

### CODE REVIEW

**Comment by sknorr** [comment]
Thanks! Looks good -- however, if there is a reasoning for why it's removed, like "can't be built anymore", "not necessary because x problem does not exist anymore", it would be great if you could include that.

**Comment by Firstyear** [comment]
Sure, I'll update this :)  Thanks for the review! I agree to wait until the DR is accepted before this merges too.

**Comment by sknorr** [comment]
Thanks a lot! Looks good. (SR still is not in yet.)

**Comment by Firstyear** [comment]
I'll follow up on the SR, thanks for the review :)

**Comment by Firstyear** [comment]
@sknorr This delete was accepted, so we can merge this now :) Thanks so much for your advice!

**Comment by sknorr** [comment]
Woo, thanks & merged!

**Pull request merged**
