### PR TITLE
drop of python 2 jsc#SLE-16747

### PR DESCRIPTION
**Pull request by lkocman**
https://code.opensuse.org/leap/features/issue/15

### CODE REVIEW

**Comment by nilxam** [comment]
technical part is still WIP

**Comment by KucharczykL** [comment]
Is this ready or do you plan to add something more?

**Comment by lkocman** [comment]
I think this is ready @KucharczykL

**Comment by KucharczykL** [comment]
@lkocman OK :) @nilxam said the technical part is still WIP but I suppose that didn't refer to this PR.

**Pull request merged**
