### PR TITLE
Add notes about KDE4 and Qt4 in Leap 15.2

### PR DESCRIPTION
**Pull request by krop**

### CODE REVIEW

**Comment by lkocman** [comment]
Thank you @krop. Target branch is Leap-15.2 so we should probably not say will be dropped in next release, but rather that package is dropped in 15.2

@fsundermeyer what would be the most typical wording?

**Comment by krop** [comment]
> Thank you @krop. Target branch is Leap-15.2 so we should probably not say will be dropped in next release, but rather that package is dropped in 15.2

Nope, unrelated to the libkdegames4 and kdesdk4-scripts removal.
Ludwig is opposed to dropping KDE4 and Qt4 in Leap 15.2, leaving users install insecure software.

The second commit warns users that installing softwares depending on these packages is a possible security risk.

**Comment by lkocman** [comment]
Ah oky, Thank you for explanation.

**Comment by fsundermeyer** [comment]
Looks good to me. However, what about adding an additional note/warning about the general consequences? Something like:

**Comment by sknorr** [comment]
As an addition: It is a good idea to avoid the word "dropped" because it is both colloquial and a bit unclear. "removed" is a much better alternative.

**Comment by krop** [comment]
> Looks good to me. However, what about adding an additional note/warning about the general consequences? Something like:

something like..?

**Comment by fsundermeyer** [comment]
It's not good using RocketChat and GitHub reviews in parallel. In RocketChatCtrl+Enter creates a newline and Enter "commits" whereas in GitHub reviews it is vice versa %-}

I have edited my original comment, you should see it now.

**Comment by krop** [comment]
LGTM, except the first sentence.
The Leap product manager wants to go against the KDE maintainers will and recommendations. We will not support the KDE4 and Qt4 packages in 15.2 and ask users to install supported versions.

**Comment by krop** [comment]
the next question is where to add this paragraph? the deprecated packages section doesn't seem to be the best place.
It's supposed to contain individual packages names, afaics

**Comment by fsundermeyer** [comment]
I suggest the "Desktop" section

**Comment by krop** [comment]
Thanks, updated.

**Pull request merged**
